# Generated by Django 6.0.2 on 2026-02-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cheque_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=200)),
                ('cheque_date', models.CharField(max_length=200)),
                ('cheque_bank', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('payee_name', models.CharField(max_length=200)),
                ('cheque_amount', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
