# Generated by Django 6.0.2 on 2026-02-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cheque_deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('cheque_bank', models.CharField(max_length=200)),
                ('cheque_amount', models.CharField(max_length=200)),
                ('deposit_bank', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('deposit_date', models.CharField(max_length=200)),
                ('deposit_slip_no', models.CharField(max_length=200)),
            ],
        ),
    ]
