# Generated by Django 6.0.2 on 2026-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cheque_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque_deposit',
            name='chequedate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
