# Generated by Django 6.0.2 on 2026-02-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_cheque_deposit_chequedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque_deposit',
            name='chequedate',
        ),
        migrations.AddField(
            model_name='cheque_deposit',
            name='remarks',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
